### ISSUE TITLE
mysql snaphot + backup

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#10]

**Comment by tsafacjo** [comment]
can i take it ?

**Comment by billmetangmo** [comment]
yes of course

**Comment by tsafacjo** [comment]
resource https://sectigostore.com/page/how-to-schedule-automatic-mysql-backups/

**Comment by tsafacjo** [comment]
@billmetangmo  https://www.loom.com/share/ac88599f47f54d58be184744e6a4cbe5?from_recorder=1&focus_title=1

I feed concerning this task !

**Comment by billmetangmo** [comment]
closed with https://github.com/mongulu-cm/manzi-mfa/pull/30
