### ISSUE TITLE
Send reminders using https://httpsms.com/

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#13]

**Comment by tsafacjo** [comment]
I will use serverless function on kunernetes power by openfaas :
https://yankeexe.medium.com/deploy-your-serverless-python-function-locally-with-openfaas-in-kubernetes-c3b564e6fd18

**Comment by tsafacjo** [comment]
I will do it with  openfaas a serveless soluton on kubernetes.
First in python, then I will move to Go lang.

**Comment by tsafacjo** [comment]
I will first do hit as cronjob on a docker container in python or go.

Then I wlil  try serveless solution like kubeless and opeenfass 

https://medium.com/nerd-for-tech/going-serverless-in-kubernetes-using-kubeless-8ef83b3f2f89


I shoud provide some general advice document a way to go document to easy make a choice.

https://medium.com/nerd-for-tech/going-serverless-in-kubernetes-using-kubeless-8ef83b3f2f89

**Comment by tsafacjo** [comment]
https://medium.com/swlh/deploy-your-private-docker-registry-as-a-pod-in-kubernetes-f6a489bf0180

**Comment by tsafacjo** [comment]
I choose the easiest solution retrieve data from postgres.

I shoudl migrate to retrieve data from easyappoitement api

**Comment by billmetangmo** [comment]
https://twiliodeved.github.io/message-segment-calculator/

**Comment by namendjo** [comment]
Statut ? @billmetangmo

**Comment by billmetangmo** [comment]
Oui c'est bon @namendjo , je le passe à done
