### ISSUE TITLE
Be sure that all meetings shoul happen at least X days before

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#15]

**Comment by tsafacjo** [comment]
still on going ?

**Comment by billmetangmo** [comment]
Oui , ici je voudrais m'assurer que les gens puissent pas réserver un meeting 2h avant donc avoir une durée mininamle d'une semaine par exemple. C'est pas supporté par défaut donc il faudrait avoir un truc avec pipedream par exemple ou lambda qui tous les jours supprime les dispos à moins d'une semaine d'une personne.

**Comment by tsafacjo** [comment]
Ok, mais il faudrait informer les utilisateurs !

**Comment by billmetangmo** [comment]
J'ai réalisé que easyappointments(EA) est vraiment pour des gens qui proposent des services en ligne et l'utilisent totalement comme scheduler. Ce qui veut dire qu'un temps libre sur easyappointments correspond à un temps de travail ou je suis disponible. Si un client le prend à la dernière minute ça me va. Ce qui n'est pas le cas pour nous ou comme c'est du temps bénévole hors temps de travail,il faut un délai pour pouvoir s'organiser. Mais EA ne supporte pas nativement cela contrairement à cal. 

Pour faire la fonctionnalité,j'ai donc été obligé de faire un workaround. Celui-ci a été pour moi de considérer de sortir les working plans de EA pour les stocker dans un store externe ( ici un datastore pipedream). Ainsi par défaut tous les working plans sont null dans EA. Les jours de RDV sont tous des wokring plan exceptions calculés chaque jour à l'aide d'un cron pipedream.
