### ISSUE TITLE
Les notes linkedin url et lien CV sont dans le RV et pas dans le profil de l'utilisateur

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#17]

**Comment by tsafacjo** [comment]
Je ne comprends pas.

**Comment by billmetangmo** [comment]
@tsafacjo voici l'explication https://www.loom.com/share/6c2bedeb02854352b71411866268d4ad

**Comment by tsafacjo** [comment]
ok, mais je pense qu'il serait plus propre de le faire dans une autre lambda, celle que je crée a uniuement vocatio à lire les données pour enrichir le datawarehouse, et  pas les modifier depuis le legacy.

**Comment by billmetangmo** [comment]
yes no soucy à ce niveau

**Comment by namendjo** [comment]
Statut ?

**Comment by billmetangmo** [comment]
Je prends le ticket

**Comment by billmetangmo** [comment]
Done dans pipedream
