### ISSUE TITLE
https is down  on manzi-mfa

### ISSUE THREAD

**Issue by tsafacjo** [mongulu-cm/manzi-mfa#38]
https is down  on manzi-mfa

**Comment by billmetangmo** [comment]
Oh j'ai réçu la notif , je pensais que c'était juste une manip que t'avait faite.
Mais visiblement ça fait 2 jours et c'est lié à ce que t'a dit https://github.com/mongulu-cm/uptime/issues/496

**Comment by tsafacjo** [comment]
il n'y rien d'explicite comme cause  sur le lien.

**Comment by billmetangmo** [comment]
It's now up and running @tsafacjo
I noticed that the certificates were not present anymore

**Comment by tsafacjo** [comment]
Cool !
