### ISSUE TITLE
call reminder for appointement

### ISSUE THREAD

**Issue by tsafacjo** [mongulu-cm/manzi-mfa#40]
https://aws.amazon.com/blogs/contact-center/automating-outbound-calling-to-customers-using-amazon-connect/

**Comment by Tchepga** [comment]
call at the start time of the appointement.

**Comment by billmetangmo** [comment]
Il n'y a pas vraiment de service qui permet de passer des appels gratuitement.
Un sms est envoyé 2h avant , j'ai rajouté un email à l'heure précise.
