### ISSUE TITLE
job scrapper 

### ISSUE THREAD

**Issue by tsafacjo** [mongulu-cm/manzi-mfa#41]
the goal is to create a scrapper that will retrieve jobs offer in France in Data Science/Engineering/ devops/ and Software Enginerring

using seleinum or whatever.

website indeed.

**Comment by tsafacjo** [comment]
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="jobLocationText"]"}

**Comment by Tchepga** [comment]
The goal is to use those job to propose the people during the interview

**Comment by namendjo** [comment]
Bonne idée générale. Mérite davantage de recherche côté UX.
