### ISSUE TITLE
déploiement continu

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#5]
CI/CD: Github Actions ou k8s ArgoCD​ / Flux

**Comment by tsafacjo** [comment]
what do you mean ?

**Comment by billmetangmo** [comment]
Currently to deploy i do it manually with kubectl but in k8s you can do Continours deployement with tool like https://fluxcd.io/ or https://argo-cd.readthedocs.io/en/stable/ . It connects to your repository and for each push , it does the kubectl ...

**Comment by billmetangmo** [comment]
@pdjiela je viens de me rendre compte que je suis idot lol 
Dans ma vidéo https://www.loom.com/share/8724813d30f14734bfd86aa0c3ceeca9 , j'ai pas remarqué il y avia en fait 2 smtp .

![Image 31-10-2024 à 14 51](https://github.com/user-attachments/assets/9b1dc1fb-4f2d-4a45-b3a8-1e7259f44259)

**Comment by billmetangmo** [comment]
Il faut juste le repasser à 1 et ce sera bon pour cette task
