### ISSUE TITLE
process job raw data and output job trends

### ISSUE THREAD

**Issue by tsafacjo** [mongulu-cm/manzi-mfa#50]
process job raw data and output job trends,

a sample of data is attached to this user story.

We could have different way to solve the problem :

  Lower case all columns values, remove (pronoum, preposition and so on ), compue word frequence ,  keep a short list let the user approve if a key word is really a skill o a technology (),
Keep a short list of skill  with specific type : python, scala, java (progrmmation language ), aws gcp (cloud provier)
compute trends for this

**Comment by fabiolatagne97** [comment]
@tsafacjo l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by tsafacjo** [comment]
file:///home/tsafacjo/Documents/workspace/manzi-mfa/jobs.json

**Comment by tsafacjo** [comment]
@CyriacAzefack  I have this amazing task for you If you are insterested

**Comment by fabiolatagne97** [comment]
@tsafacjo l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by tsafacjo** [comment]
@billmetangmo  I have created the first one.

**Comment by billmetangmo** [comment]
Super
