### ISSUE TITLE
Network issue with node paas-kubernetes-2

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#63]
https://record.reverb.chat/s/nzhammpebRAhyc3LNTaO
kubectl label nodes paas-kubernetes node-type=data-access pour pouvoir pas sélcetionner paas-kubernetes-2

**Comment by fabiolatagne97** [comment]
@billmetangmo l' issue ne contient aucun label. L'email automatique de relai n'a donc pas été envoyé. D'ici 3 jours si aucun label n'est ajouté , il n'y aura aucune communication automatique sur l'issue

**Comment by billmetangmo** [comment]
Ueful tools:
- https://github.com/bloomberg/goldpinger

**Comment by fabiolatagne97** [comment]
@billmetangmo merci d'avoir remli les tags à temps.
Un email automatique a été envoyé :) .
N'oublie pas d'envoyer également un message dans le groupe whatsapp.

**Comment by billmetangmo** [comment]
Refonctionne après avoir reboot la machine.
