### ISSUE TITLE
Create a webhook to save all event store on PostgreSQL

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/manzi-mfa#7]
- Serverless k8s: https://knative.dev/docs/install/
- Chalice: https://github.com/aws/chalice 
- Hasura: https://hasura.io/ ( to put data to postgresql directly from webhooks

**Comment by tsafacjo** [comment]
J'ai soucis ,
 je ne parviens pas à avoir le DNS de la postgre de l'exterieur, celui que j'ai c'est uniquement valable dans le cluster Kuberneste.

**Comment by billmetangmo** [comment]
Oui c'est normal, il faut changer le service postgresql de ClusterIP vers LoadBalancer.
Pour en savoir plus: https://www.youtube.com/watch?v=T4Z7visMM4E
Je viens de l'activer.

**Comment by tsafacjo** [comment]
I need to complete the CI/CD part

**Comment by billmetangmo** [comment]
Rfers to https://github.com/mongulu-cm/manzi-mfa/commit/0063d0926a876cb4c05bbd1fad0f6871682c0316
